services:
  - type: web
    name: soccer-betting
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: ML_SKIP_STARTUP_TRAIN
        value: "1"
      # Persist prediction cache under data/ so it survives restarts
      - key: PREDICTIONS_CACHE_PATH
        value: "/app/data/predictions_cache.json"
      - key: ODDS_API_KEY
        sync: false
      - key: ODDS_API_REGIONS
        value: "uk,eu,us"
      - key: TZ
        value: UTC
      # Avoid bursty recompute in production; rely on snapshots/offline jobs
      - key: ALLOW_ON_DEMAND_PREDICTIONS
        value: "0"
    disk:
      name: snapshot-data
      mountPath: /app/data
      sizeGB: 1
    previews:
      enabled: true
