services:
  - type: web
    name: soccer-betting
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: ML_SKIP_STARTUP_TRAIN
        value: "1"
      # Persist prediction cache under data/ so it survives restarts
      - key: PREDICTIONS_CACHE_PATH
        value: "/app/data/predictions_cache.json"
      - key: ODDS_API_KEY
        sync: false
      - key: ODDS_API_REGIONS
        value: "uk,eu,us"
      - key: TZ
        value: UTC
      # Avoid bursty recompute in production; rely on snapshots/offline jobs
      - key: ALLOW_ON_DEMAND_PREDICTIONS
        value: "0"
      # Token to protect cron endpoints (optional but recommended)
      - key: REFRESH_CRON_TOKEN
        sync: false
      # Optional: publish daily summary JSON to GitHub
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: GITHUB_BRANCH
        value: main
      - key: GITHUB_PATH_PREFIX
        value: artifacts/daily_summaries
    disk:
      name: snapshot-data
      mountPath: /app/data
      sizeGB: 1
    previews:
      enabled: true
    
    
    # Scheduled jobs: warm odds hourly, run overnight reconciliation daily
    cronJobs:
      - name: warm-odds-hourly
        schedule: "0 * * * *"  # hourly on the hour (UTC)
        command: |
          TOKEN=${REFRESH_CRON_TOKEN:-} ; \
          curl -s -X POST http://localhost:${PORT:-8000}/api/cron/refresh-bovada -H "Authorization: Bearer $TOKEN"
      - name: snapshot-csv-hourly
        schedule: "5 * * * *"  # hourly +5 minutes
        command: |
          TOKEN=${REFRESH_CRON_TOKEN:-} ; \
          curl -s -X POST "http://localhost:${PORT:-8000}/api/cron/snapshot-csv?league=ALL&include_odds_api=true" -H "Authorization: Bearer $TOKEN"
      - name: capture-closing-nightly
        schedule: "20 3 * * *"  # daily at 03:20 UTC (before reconciliation)
        command: |
          TOKEN=${REFRESH_CRON_TOKEN:-} ; \
          curl -s -X POST "http://localhost:${PORT:-8000}/api/cron/capture-closing?force=true" -H "Authorization: Bearer $TOKEN"
      - name: overnight-reconciliation
        schedule: "30 3 * * *"  # daily at 03:30 UTC
        command: |
          TOKEN=${REFRESH_CRON_TOKEN:-} ; \
          curl -s -X POST http://localhost:${PORT:-8000}/api/cron/daily-update -H "Authorization: Bearer $TOKEN"
      - name: auto-tune-blend-weekly
        schedule: "0 4 * * 1"  # every Monday 04:00 UTC (after nightly jobs)
        command: |
          TOKEN=${REFRESH_CRON_TOKEN:-} ; \
          curl -s -X POST http://localhost:${PORT:-8000}/api/cron/auto-tune-blend -H "Authorization: Bearer $TOKEN"
